Repository project-pareto/project-pareto, pull requests merged in 2022-04, with the labels that each got.

#118 Fixing Warning in get_data
  pareto/utilities/get_data.py
Labels: bug, Priority:Normal

#121 Clean up of old main function which has been replaced by the run files.
  pareto/operational_water_management/operational_produced_water_optimization_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
Labels: Priority:Normal

#112 Adding plot_scatter()
  docs/utilities/Results.rst
  docs/utilities/plot_scatter_1.png
  docs/utilities/plot_scatter_2.png
  docs/utilities/plot_scatter_3.png
  docs/utilities/plot_scatter_4.png
  pareto/case_studies/visualization_test_data.xlsx
  pareto/tests/test_plot_bars.py
  pareto/tests/test_plot_scatter.py
  pareto/utilities/results.py
Labels: documentation, enhancement, tests, Priority:Normal

#115 Node Capacity - New
  docs/model_library/strategic_water_management/index.rst
  pareto/case_studies/Input_File_Track_Changes.txt
  pareto/case_studies/input_data_generic_strategic_case_study_LAYFLAT_FULL.xlsx
  pareto/case_studies/small_strategic_case_study.xlsx
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/run_strategic_model_water_quality.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/tests/test_strategic_model.py
Labels: Priority:Normal

#119 Add Gurobi troubleshooting files to gitignore
  .gitignore
Labels: enhancement, Priority:High

#117 Set slacks to zero
  .stagedfright/checks.py
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/utilities/results.py
Labels: enhancement, Priority:High

#122 Water treatment case study
  pareto/case_studies/strategic_water_treatment_toy_case_study_t10.xlsx
  pareto/case_studies/strategic_water_treatment_toy_case_study_t20.xlsx
  pareto/case_studies/strategic_water_treatment_toy_case_study_t52.xlsx
  pareto/strategic_water_management/run_strategic_model.py
Labels: Priority:Normal
