Repository project-pareto/project-pareto, pull requests merged in 2022-03, with the labels that each got.

#89 Pipeline Config Options
  .stagedfright/checks.py
  pareto/case_studies/Input_File_Track_Changes.txt
  pareto/case_studies/input_data_generic_strategic_case_study_LAYFLAT_FULL.xlsx
  pareto/case_studies/small_strategic_case_study.xlsx
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/tests/test_strategic_model.py
Labels: bug, Priority:High

#105 PARETO - Sphinx documentation
  docs/Makefile
  docs/_static/favicon.ico
  docs/_static/logo-print-hd.jpg
  docs/conf.py
  docs/copyright.rst
  docs/faq.rst
  docs/getting_started/index.rst
  docs/img/PARETO_1.png
  docs/img/PARETO_2.png
  docs/img/PARETO_2a.png
  docs/img/PARETO_3.png
  docs/index.rst
  docs/license.rst
  docs/make.bat
  docs/model_library/index.rst
  docs/model_library/operational_water_management/index.rst
  docs/model_library/strategic_water_management/index.rst
  docs/tutorials_examples/index.rst
  docs/utilities/Get_Data.rst
  docs/utilities/Results.rst
  docs/utilities/generate_report_1.PNG
  docs/utilities/generate_report_2.PNG
  docs/utilities/get_data_1.PNG
  docs/utilities/get_data_2.PNG
  docs/utilities/index.rst
  docs/utilities/plot_bars_1.PNG
  docs/utilities/plot_sankey_1.PNG
  requirements-dev.txt
Labels: documentation, Priority:High

#110 Add configuration for ReadTheDocs builds
  .readthedocs.yaml
Labels: Priority:High

#114 Fix missing files Sphinx warnings due to file names case sensitivity
  .readthedocs.yaml
  docs/utilities/generate_report_1.png
  docs/utilities/generate_report_2.png
  docs/utilities/get_data_1.png
  docs/utilities/get_data_2.png
  docs/utilities/plot_bars_1.png
  docs/utilities/plot_sankey_1.png
Labels: documentation, Priority:Normal

#116 Fixing scaling factors
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/tests/test_solvers.py
  requirements-dev.txt
Labels: bug, enhancement, Priority:High
