Repository project-pareto/project-pareto, pull requests merged in 2022-10, with the labels that each got.

#171 Fix Water Quality Operational Model bug
  .stagedfright/checks.py
  pareto/operational_water_management/operational_produced_water_optimization_model.py
  pareto/tests/test_operational_model.py
  pareto/utilities/results.py
Labels: Priority:High, Treatment

#166 Adding some badges to README.md
  README.md
Labels: Priority:Normal

#159 Convert docs for operational model to ASCII LaTeX
  docs/model_library/operational_water_management/index.rst
Labels: documentation, Priority:High
