Repository project-pareto/project-pareto, pull requests merged in 2023-01, with the labels that each got.

#184 Strategic model - add convert default value for p_pi_Trucking from user units to model units
  pareto/strategic_water_management/strategic_produced_water_optimization.py
Labels: Priority:Normal

#186 Clean up small strategic case study and turn off default scaling for strategic model
  pareto/case_studies/small_strategic_case_study.xlsx
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/tests/test_strategic_model.py
Labels: Priority:Normal

#189 UI Display Units
  pareto/case_studies/EXAMPLE_INPUT_DATA_FILE_generic_operational_model.xlsx
  pareto/operational_water_management/run_operational_model.py
  pareto/tests/test_operational_model.py
  pareto/tests/test_strategic_model.py
  pareto/utilities/get_data.py
Labels: Priority:Normal, UI

#201 check HTTP status code before attempting to decode JSON
  pareto/utilities/get_data.py
Labels: bug
