Repository project-pareto/project-pareto, pull requests merged in 2023-07, with the labels that each got.

#260 Add dependencies removed in IDAES 2.1
  pareto/tests/test_headers.py
  setup.py
Labels: Priority:High

#256 Update tutorials documentation
  docs/tutorials_examples/index.rst
Labels: Priority:Normal

#241 Apply unified sets to Operational Model
  .stagedfright/checks.py
  docs/model_library/operational_water_management/index.rst
  pareto/case_studies/operational_generic_case_study.xlsx
  pareto/operational_water_management/operational_produced_water_optimization_model.py
  pareto/operational_water_management/run_operational_model.py
  pareto/tests/test_operational_model.py
Labels: Priority:High, operational model

#246 Add visualization demo Jupyter notebooks
  .stagedfright/checks.py
  docs/tutorials_examples/index.rst
  pareto/examples/strategic_model_general_demo/strategic_model_general_demo.ipynb
  pareto/examples/strategic_model_general_demo/strategic_toy_network.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_NRA.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_RCA.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_RNA.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_RSA.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_desalination_sites.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_desalination_technologies.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_initial_treatment_capacity.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_pad_storage_initial_quality.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_pad_water_quality.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_storage_initial_quality.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_treatment_OPEX.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_treatment_capacities.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_treatment_capacity_increments.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_treatment_efficiency.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_treatment_expansion_cost.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_treatment_removal_efficiency.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_treatment_sites.png
  pareto/examples/strategic_model_treatment_module_demo/data_input_treatment_technologies.png
  pareto/examples/strategic_model_treatment_module_demo/strategic_model_treatment_module_demo.ipynb
  pareto/examples/strategic_model_treatment_module_demo/strategic_toy_network.png
  pareto/examples/visualization_demos/plot_bars_demo.ipynb
  pareto/examples/visualization_demos/plot_sankey_demo.ipynb
  pareto/examples/visualization_demos/plot_scatter_demo.ipynb
  pareto/examples/visualization_demos/visualization_demos_data.xlsx
  pareto/tests/test_plot_bars.py
  pareto/tests/test_plot_sankey.py
  pareto/tests/test_plot_scatter.py
  pareto/tests/visualization_test_data.xlsx
  pareto/utilities/get_data.py
  pareto/utilities/results.py
Labels: Priority:Normal

#262 Ensure docs use correct support email list address
  docs/conf.py
  docs/faq.rst
  docs/getting_started/index.rst
  docs/index.rst
Labels: Priority:High

#254 added tests for bounding functions & utilities
  .stagedfright/checks.py
  pareto/tests/test_utilities.py
  pareto/utilities/bounding_functions.py
  pareto/utilities/model_modifications.py
Labels: Priority:Normal
