Repository project-pareto/project-pareto, pull requests merged in 2023-02, with the labels that each got.

#207 Infrastructure Buildout Bug Fix
  .stagedfright/checks.py
  pareto/utilities/results.py
Labels: bug

#206 add reduced treatment demo case study
  docs/case_studies/index.rst
  docs/img/Baseline.png
  docs/img/Pipeline Shutdown.png
  docs/img/Reduced Completions Demand.png
  docs/img/Reduced Flowback.png
  docs/img/SRA.png
  docs/img/strategic_permian_demo.png
  pareto/case_studies/strategic_permian_demo.xlsx
  pareto/tests/test_strategic_model.py
Labels: Priority:Normal

#203 Feasibility check
  pareto/operational_water_management/run_operational_model.py
  pareto/strategic_water_management/run_strategic_model.py
  pareto/tests/test_strategic_model.py
  pareto/utilities/results.py
Labels: Priority:High
