Repository project-pareto/project-pareto, pull requests merged in 2024-05, with the labels that each got.

#313 Adding MD & MVC surrogates
  .gitattributes
  pareto/case_studies/strategic_treatment_demo_surrogates.xlsx
  pareto/conftest.py
  pareto/examples/strategic_model_general_demo/strategic_model_general_demo.ipynb
  pareto/models_extra/CM_module/cm_utils/data_parser.py
  pareto/models_extra/CM_module/cm_utils/gen_utils.py
  pareto/models_extra/CM_module/cm_utils/run_utils.py
  pareto/models_extra/CM_module/cm_utils/spec_utils.py
  pareto/models_extra/CM_module/models/qcp_br.py
  pareto/models_extra/desalination_models/mee_mvr.py
  pareto/operational_water_management/operational_produced_water_optimization_model.py
  pareto/strategic_water_management/md_keras/fingerprint.pb
  pareto/strategic_water_management/md_keras/idaes_info.json
  pareto/strategic_water_management/md_keras/keras_metadata.pb
  pareto/strategic_water_management/md_keras/saved_model.pb
  pareto/strategic_water_management/md_keras/variables/variables.data-00000-of-00001
  pareto/strategic_water_management/md_keras/variables/variables.index
  pareto/strategic_water_management/mvc_keras/fingerprint.pb
  pareto/strategic_water_management/mvc_keras/idaes_info.json
  pareto/strategic_water_management/mvc_keras/keras_metadata.pb
  pareto/strategic_water_management/mvc_keras/saved_model.pb
  pareto/strategic_water_management/mvc_keras/variables/variables.data-00000-of-00001
  pareto/strategic_water_management/mvc_keras/variables/variables.index
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/tests/test_strategic_model.py
  pareto/tests/toy_case_study.py
  pareto/utilities/get_data.py
  pareto/utilities/model_modifications.py
  pareto/utilities/results.py
  pareto/utilities/solvers.py
  setup.py
  stagedfright.py
Labels: Priority:High

#290 Add subsurface risk calculation to strategic_produced_water_optimization.py
  docs/model_library/index.rst
  docs/model_library/subsurface_risk_calculation/index.rst
  pareto/case_studies/strategic_permian_demo.xlsx
  pareto/case_studies/strategic_small_case_study.xlsx
  pareto/case_studies/strategic_treatment_demo.xlsx
  pareto/case_studies/strategic_treatment_demo_surrogates.xlsx
  pareto/case_studies/workshop_baseline_all_data.xlsx
  pareto/examples/multiobjective_optimization/seismicity_vs_cost_MOO.ipynb
  pareto/examples/strategic_model_general_demo/strategic_model_general_demo.ipynb
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/tests/test_strategic_model.py
  pareto/tests/test_utilities.py
  pareto/utilities/get_data.py
  pareto/utilities/results.py
  pareto/utilities/units_support.py
Labels: Priority:High, binary files changes

#307 add MD flowsheet with NaCl and Jupyter notebook
  pareto/examples/Membrane_Distillation/MD_PARETO.ipynb
  pareto/examples/Membrane_Distillation/MDflowsheet.png
  pareto/models_extra/desalination_models/MD_single_stage_continuous_recirculation.py
Labels: Priority:Normal

#291 Input Data Error Handling and Infeasibility Detection
  docs/utilities/Get_Data.rst
  pareto/examples/multiobjective_optimization/seismicity_vs_cost_MOO.ipynb
  pareto/examples/strategic_model_general_demo/strategic_model_general_demo.ipynb
  pareto/examples/strategic_model_treatment_module_demo/strategic_model_treatment_module_demo.ipynb
  pareto/examples/visualization_demos/plot_bars_demo.ipynb
  pareto/examples/visualization_demos/plot_sankey_demo.ipynb
  pareto/examples/visualization_demos/plot_scatter_demo.ipynb
  pareto/models_extra/CM_module/case_studies/CM_large_permian.xlsx
  pareto/models_extra/CM_module/case_studies/CM_small_permian.xlsx
  pareto/models_extra/CM_module/cm_utils/data_parser.py
  pareto/models_extra/CM_module/cm_utils/run_utils.py
  pareto/models_extra/CM_module/run_base.py
  pareto/models_extra/CM_module/run_infrastructure_analysis.py
  pareto/models_extra/CM_module/run_optimal_desal.py
  pareto/models_extra/CM_module/screening_tool.ipynb
  pareto/models_extra/CM_module/set_param_list.py
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/tests/strategic_toy_case_study_data_error.xlsx
  pareto/tests/strategic_toy_case_study_data_error2.xlsx
  pareto/tests/strategic_toy_case_study_data_warning.xlsx
  pareto/tests/strategic_toy_case_study_infeasibility_capacity.xlsx
  pareto/tests/strategic_toy_case_study_infeasibility_demand.xlsx
  pareto/tests/test_cm_qcp.py
  pareto/tests/test_operational_model.py
  pareto/tests/test_plot_bars.py
  pareto/tests/test_plot_scatter.py
  pareto/tests/test_strategic_model.py
  pareto/tests/test_utilities.py
  pareto/utilities/get_data.py
  pareto/utilities/process_data.py
Labels: Priority:High
