Repository project-pareto/project-pareto, pull requests merged in 2024-06, with the labels that each got.

#311 Integrate desalination models
  pareto/examples/integrated_desalination_jupyter_notebooks/integrated_optimization_md_jupyter_notebook.ipynb
  pareto/examples/integrated_desalination_jupyter_notebooks/integrated_optimization_mvr_jupyter_notebook.ipynb
  pareto/models_extra/CM_module/case_studies/CM_integrated_desalination_demo.xlsx
  pareto/models_extra/CM_module/case_studies/CM_large_permian.xlsx
  pareto/models_extra/CM_module/case_studies/CM_small_permian.xlsx
  pareto/models_extra/Integrate_desal/integrated_models/backcalculate_mvr_design.py
  pareto/models_extra/Integrate_desal/integrated_models/integrated_optimization_md.py
  pareto/models_extra/Integrate_desal/integrated_models/integrated_optimization_mvr.py
  pareto/models_extra/Integrate_desal/models/qcp_desal.py
  pareto/tests/test_integrated_optimization_mvr.py
Labels: Priority:High

#324 Adding surrogate training notebook
  pareto/examples/desalination_jupyter_notebooks/desalination_surrogate_training.ipynb
  pareto/examples/desalination_jupyter_notebooks/md_data.csv
  pareto/examples/desalination_jupyter_notebooks/mvc_data.csv
Labels: Priority:Normal

#280 Adapt get_data() to pandas v2 API
  .github/workflows/checks.yml
  pareto/strategic_water_management/run_strategic_model.py
  pareto/tests/test_data.py
  pareto/tests/test_environment.py
  pareto/utilities/get_data.py
  pareto/utilities/results.py
  requirements-dev.txt
  setup.py
Labels: Priority:Normal

#258 154 update kpis for treatment
  docs/model_library/strategic_water_management/index.rst
  pareto/case_studies/operational_generic_case_study.xlsx
  pareto/case_studies/strategic_permian_demo.xlsx
  pareto/case_studies/strategic_small_case_study.xlsx
  pareto/case_studies/strategic_toy_case_study.xlsx
  pareto/case_studies/strategic_treatment_demo.xlsx
  pareto/case_studies/strategic_treatment_demo_surrogates.xlsx
  pareto/case_studies/workshop_baseline_all_data.xlsx
  pareto/models_extra/CM_module/cm_utils/data_parser.py
  pareto/strategic_water_management/run_strategic_model.py
  pareto/strategic_water_management/strategic_produced_water_optimization.py
  pareto/tests/strategic_small_case_study_load_removaleff.xlsx
  pareto/tests/strategic_toy_case_study_data_error2.xlsx
  pareto/tests/strategic_toy_case_study_data_warning.xlsx
  pareto/tests/strategic_toy_case_study_infeasibility_capacity.xlsx
  pareto/tests/strategic_toy_case_study_infeasibility_demand.xlsx
  pareto/tests/test_strategic_model.py
  pareto/tests/test_utilities.py
  pareto/utilities/get_data.py
  pareto/utilities/process_data.py
  pareto/utilities/results.py
Labels: Priority:High, binary files changes

#325 Citations
  CITATION.cff
  README.md
  docs/citing.rst
  docs/index.rst
Labels: Priority:Normal

#330 Updating copyright to 2024
  pareto/models_extra/desalination_models/MD_single_stage_continuous_recirculation.py
Labels: Priority:Normal

#333 Resolve ModuleNotFoundErrors in #332
  .github/workflows/checks.yml
  pareto/examples/integrated_desalination_jupyter_notebooks/integrated_optimization_md_jupyter_notebook.ipynb
  pareto/examples/integrated_desalination_jupyter_notebooks/integrated_optimization_mvr_jupyter_notebook.ipynb
  pareto/models_extra/CM_module/cm_utils/__init__.py
  pareto/models_extra/CM_module/models/__init__.py
  pareto/models_extra/desalination_models/__init__.py
  pareto/models_extra/integrate_desal/__init__.py
  pareto/models_extra/integrate_desal/integrated_models/__init__.py
  pareto/models_extra/integrate_desal/integrated_models/backcalculate_mvr_design.py
  pareto/models_extra/integrate_desal/integrated_models/integrated_optimization_md.py
  pareto/models_extra/integrate_desal/integrated_models/integrated_optimization_mvr.py
  pareto/models_extra/integrate_desal/models/__init__.py
  pareto/models_extra/integrate_desal/models/qcp_desal.py
  pareto/tests/test_integrated_optimization_mvr.py
  setup.py
Labels: Priority:High
